DROP TABLE IF EXISTS offer;

CREATE TABLE offer (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  dat DATE NOT NULL,
  tim TIME NOT NULL,
  home VARCHAR(50) NOT NULL,
  away VARCHAR(50) NOT NULL,
  type1 DECIMAL(6,2) NOT NULL,
  typex DECIMAL(6,2) NOT NULL,
  type2 DECIMAL(6,2) NOT NULL,
  type1x DECIMAL(6,2) NOT NULL,
  type2x DECIMAL(6,2) NOT NULL
);

CREATE TABLE ticket (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  home VARCHAR(50) NOT NULL,
  away VARCHAR(50) NOT NULL,
  tip VARCHAR(2) NOT NULL,
  kvota DECIMAL(6,2) NOT NULL,
  total DECIMAL(6,2) NOT NULL
  );
  
  CREATE TABLE users (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(50) NOT NULL,
  surname VARCHAR(50) NOT NULL,
  balance DECIMAL(6,2) NOT NULL
  );